name: Publish to NPM
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  merge_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v9
        with:
          version: 2.0.17
          actions-cache-folder: "emsdk-cache"
      - name: Install modules
        run: cd js && npm install
      - name: Build
        run: cd js && ./build.sh
      - name: Run tests
        run: cd js && npm test
      - name: Try Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd js && ./publish.sh
